service: sls-appsync-backend
org: nicklloyd
package:
  individually: true
provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:REGION}
  stage: ${opt:stage, env:AWS_STAGE, 'dev'}
  environment:
    service: sls-appsync-backend
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1 # Use http keep-alive for AWS connections

plugins:
  - serverless-dotenv-plugin
  - serverless-appsync-plugin
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-offline

custom:
  prune:
    automatic: true
    number: 5 # Number of versions to keep
  serverless-offline:
    allowCache: true
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  accountId: ${env:AWS_ACCOUNT_ID}
  appSync:
    name: sls-appsync-api
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ${env:REGION}
      defaultAction: ALLOW
      userPoolId: { Ref: CognitoUserPool }
    serviceRole: 'AppSyncServiceRole'
    dataSources: ${file(resources/data-sources.yml)}

functions:
  - ${file(resources/functions.yml)}

resources:
  # Roles
  - ${file(resources/roles.yml)}
