Resources:
  TodosTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${env:TODOS_TABLE}-${env:STAGE}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
  UsersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${env:USERS_TABLE}-${env:STAGE}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: email
          KeyType: RANGE
